### ISSUE TITLE
ColorScheme - Support semantic highlighting

### ISSUE THREAD

**Issue by pykong** [meetio-theme/sublime-meetio-theme#17]
Since version 3.1 Sublime Text offers native support for semantic highlighting, a feature formerly requiring [ColorCoder](https://github.com/vprimachenko/Sublime-Colorcoder).

See: [Hashed Syntax Highlighting](https://www.sublimetext.com/docs/3/color_schemes.html#hashed_syntax_highlighting) (_aka Semantic Highlighting)_

I see a lot of potential for this feature to enhance readability/understability of code.
However so far I have not seen any color scheme which makes good use of this feature.
The problem being that the dynamic nature of where only a color range is given for the semantic highlighting to chose from makes balancing colors difficult.

Also to the best of my knowledge there is no dark color scheme variant in existence to offer this feature (only the inbuilt Celeste scheme, which is bright.)

It would IMHO require a very apt designer to balance out colours in a way to make the semantic highlighting stand out while not transforming the color scheme into an ugly mess.

@mauroreisvieira If you want a real challenge and make `Meetio` to stand-out even further above other UI packs this would be the perfect opportunity to invest your enthusiasm into. Offering a sane and well working semantic highlight could become a unique selling point of `Meetio`.

**Comment by mauroreisvieira** [comment]
Hi @pykong at the moment I do not see great advantages in using Hash Syntax Highlighting.
I at the beginning of Meetio development did some testing of this approach, but I found it a mess.

Because it's strange for me to assign different colors to the same or similar scopes.

Just change the scheme to Celeste that we realize this.

<img width="476" alt="Screenshot 2019-06-18 at 10 30 18" src="https://user-images.githubusercontent.com/3084774/59670597-17be5080-91b4-11e9-9c95-2387be7e639d.png">

**Comment by pykong** [comment]
As I said, it is a question of how to delicately balance differentiability of colours against preventing the color scheme to become a mess. 

Of course at hand we want to stress the similarity of related syntax element, while at the same time allowing individual instances to be differentiated.

I just close this issue for now. Feel free to reopen if you ever want to give it another shot.
